#!/usr/bin/env python3
"""Extract the hostname-relevant part of Unicode's confusables table.

    mise run fetch-confusables

`SERVER.md` calls homoglyph anchors "a spoofing problem with a technical answer
— punycode display and confusable detection at ingest — not a dispute". The
technical answer is UTS 39, and UTS 39 is a data file rather than a clever
function. Approximating it with a hand-written list of lookalikes would be the
kind of plausible-looking assertion this project refuses elsewhere.

The full table is 745 KB and 6,565 mappings, most of them irrelevant here: a
hostname is punycode by the time we compare it, so the only mappings that matter
are the ones whose *target* is made of characters a hostname can contain. That
is 1,565 of them, and about 16 KB — small enough to vendor, so a security check
never depends on the network being up.

Kept as a script rather than a documented curl, so the provenance is
reproducible and the version is recorded next to the data.
"""
from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

SOURCE = "https://www.unicode.org/Public/security/latest/confusables.txt"
OUT = Path(__file__).resolve().parents[2] / "src" / "podshl" / "server" / "confusables.json"

HOSTNAME_CHARS = set("abcdefghijklmnopqrstuvwxyz0123456789-.")


def main() -> None:
    print(f"fetching {SOURCE}")
    with urllib.request.urlopen(SOURCE, timeout=60) as r:
        raw = r.read().decode("utf-8-sig")

    version = re.search(r"^# Version: (.+)$", raw, re.M).group(1).strip()
    date = re.search(r"^# Date: (.+)$", raw, re.M).group(1).strip()

    mappings: dict[str, str] = {}
    for line in raw.splitlines():
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split(";")]
        if len(parts) < 2:
            continue
        try:
            source = chr(int(parts[0], 16))
            target = "".join(chr(int(c, 16)) for c in parts[1].split())
        except ValueError:
            continue
        if not target or any(c not in HOSTNAME_CHARS for c in target.lower()):
            continue
        if source.lower() == target.lower():
            continue
        mappings[source] = target.lower()

    OUT.write_text(json.dumps(
        {
            "$comment": "Generated by scripts/dev/fetch_confusables.py. The subset of "
                        "UTS 39 whose targets are hostname-legal — the only part "
                        "that can matter once a host is punycode.",
            "source": SOURCE,
            "unicode_version": version,
            "unicode_date": date,
            "mappings": mappings,
        },
        indent=1, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
    print(f"  UTS 39 {version}, dated {date}")
    print(f"  {len(mappings)} hostname-relevant mappings -> {OUT.relative_to(OUT.parents[3])}")


if __name__ == "__main__":
    main()
